on:
  pull_request:
    types: [closed]
name: Clean up
env:
  CLUSTER_REPO: ${{ secrets.CLUSTER_REPO }}
jobs:
  tear_down:
    name: Tear down feature branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Kustomized Namespace - Cleanup Overlay
      uses: zyngl/cleanup_kustomized_namespace@v0.9.0
      env:
        TOKEN: ${{ secrets.TOKEN }}
