# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  pull_request:
    types: [labeled]
name: Build, push, and deploy
env:
  SERVICE: red
  TARGET_IMAGE: dudo/red
jobs:
  docker:
    if: github.event.label.name == 'deploy'
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build
      run: docker build -t $TARGET_IMAGE:${GITHUB_SHA::7} .
    - name: Push
      run: docker push $TARGET_IMAGE:${GITHUB_SHA::7}
  deploy:
    name: Deploy to Cluster
    runs-on: ubuntu-latest
    needs: docker
    env:
      CLUSTER_REPO: dudo/k8s_colors
    steps:
    - name: Kustomized Namespace - Create Overlay
      env:
        TOKEN: ${{ secrets.TOKEN }}
      uses: zyngl/create_kustomized_namespace@v1.3.0
      with:
        args: --flux
