on:
  pull_request:
    types: [unlabeled]
name: Clean up
env:
  SERVICE: red
  CLUSTER_REPO: dudo/k8s_colors
jobs:
  tear_down:
    if: github.event.label.name == 'deploy'
    name: Tear down feature branch
    runs-on: ubuntu-latest
    steps:
    - name: Kustomized Namespace - Cleanup Overlay
      env:
        TOKEN: ${{ secrets.TOKEN }}
      uses: zyngl/cleanup_kustomized_namespace@v1.2.0
      with:
        args: --flux
