# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on:
  pull_request:
    types: [labeled]
name: Build, push, and deploy
env:
  SERVICE: ${{ secrets.SERVICE }}
  TARGET_IMAGE: ${{ secrets.TARGET_IMAGE }}
jobs:
  docker:
    name: Build and push Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Registry
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build
      run: docker build -t $TARGET_IMAGE:${GITHUB_SHA::7} .
    - name: Push
      run: docker push $TARGET_IMAGE:${GITHUB_SHA::7}
  deploy:
    name: Deploy to Cluster
    runs-on: ubuntu-latest
    needs: docker
    env:
      CLUSTER_REPO: ${{ secrets.CLUSTER_REPO }}
    steps:
    - uses: actions/checkout@v1
    - name: Kustomized Namespace - Create Overlay
      uses: zyngl/create_kustomized_namespace@v0.9.0
      env:
        TOKEN: ${{ secrets.TOKEN }}
